services:
  postgres:
    image: postgres:16-alpine
    container_name: tidy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tidy
      POSTGRES_PASSWORD: tidy_dev_password
      POSTGRES_DB: tidy_db
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U tidy -d tidy_db"
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: tidy_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tidy
      MINIO_ROOT_PASSWORD: tidy_dev_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_:/data

volumes:
  minio_:
