require_relative '../../../node_modules/.pnpm/@capacitor+ios@8.3.4_@capacitor+core@7.6.1/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '16.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/.pnpm/@capacitor+ios@8.3.4_@capacitor+core@7.6.1/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/.pnpm/@capacitor+ios@8.3.4_@capacitor+core@7.6.1/node_modules/@capacitor/ios'
  pod 'CapacitorCommunitySqlite', :path => '../../../node_modules/.pnpm/@capacitor-community+sqlite@6.0.2_@capacitor+core@7.6.1/node_modules/@capacitor-community/sqlite'
  pod 'CapacitorApp', :path => '../../../node_modules/.pnpm/@capacitor+app@7.1.2_@capacitor+core@7.6.1/node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../../node_modules/.pnpm/@capacitor+camera@7.0.5_@capacitor+core@7.6.1/node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/.pnpm/@capacitor+filesystem@7.1.8_@capacitor+core@7.6.1/node_modules/@capacitor/filesystem'
  pod 'CapacitorNetwork', :path => '../../../node_modules/.pnpm/@capacitor+network@7.0.4_@capacitor+core@7.6.1/node_modules/@capacitor/network'
  pod 'CapacitorShare', :path => '../../../node_modules/.pnpm/@capacitor+share@7.0.4_@capacitor+core@7.6.1/node_modules/@capacitor/share'
  pod 'CapacitorSecureStoragePlugin', :path => '../../../node_modules/.pnpm/capacitor-secure-storage-plugin@0.11.0_@capacitor+core@7.6.1/node_modules/capacitor-secure-storage-plugin'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
